[package]
name = "ant_io"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_ant = { git = "https://github.com/LKBaka/RustAnt.git" }
libloading = "0.8.8"
once_cell = "1.21.3"

[lib]
name = "io"
crate-type = ["dylib"]

[profile]
dev.lto = true
release.lto = true
